### ISSUE TITLE
Create Hello World Flask App

### ISSUE THREAD

**Issue by cobocombo** [cobocombo/Listify#8]
The decision has been made to use Heroku with flask instead of Back4App. Now we need to get a basic flask app going locally.

## Requirements:

* Setup python virtual environment for development in Backend folder.
* Install flask if not already.
* Create basic hello world for index app route.

**Comment by dynaput247** [comment]
Hello
May I work on opened issues?
If you need my help, contact with me:
telegram: https://t.me/dynaput247
discord: MVP (84478447)
gmail: toptalent48@gmail.com
skype: live:.cid.b5e7c8f996fa441a
